# Generated by Django 5.1.1 on 2024-10-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_alter_webhook_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
